### ISSUE TITLE
react-shallow-renderer 16.14.0 breaks Jest

### ISSUE THREAD

**Issue by nstepien** [NMinhNguyen/react-shallow-renderer#97] opened 2020-10-21 11:54 UTC
```
 FAIL  src/utils/columnUtils.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    D:\repos\react-data-grid\node_modules\react-shallow-renderer\index.js:10
    export {default} from './src/ReactShallowRenderer';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at new Script (node:vm:100:7)
      at Object.<anonymous> (node_modules/react-test-renderer/shallow.js:3:18)
```

Jest doesn't support esm yet, and modules under `node_modules` aren't transpiled by default, so this is going to break builds.
For example: https://github.com/adazzle/react-data-grid/pull/2097/checks?check_run_id=1286474140

**Comment by NMinhNguyen** [comment] 2020-10-21 11:57
Duplicate of #96. Install the newly published `16.4.1` version.

**Comment by nstepien** [comment] 2020-10-21 11:58
@NMinhNguyen `16.4.1` doesn't fix it, please read my bug report carefully and reopen this issue.

**Closed by NMinhNguyen** 2020-10-21 11:57 UTC

**Comment by NMinhNguyen** [comment] 2020-10-21 12:02
> @NMinhNguyen 16.4.1 doesn't fix it, please read my bug report carefully and reopen this issue.

Can you confirm if this is still an issue? You appear to have deleted your comment.

**Comment by nstepien** [comment] 2020-10-21 12:05
Yes sorry, had an npm caching issue, 16.4.1 works great now, thanks.
